### PR TITLE
homepage ui added with menu and menu card component

### PR DESCRIPTION
**Pull request by sanketr43**
Zenkart-Homepage

### CODE REVIEW

**Review by sanket4120 — COMMENTED** [review]
You can use variable names for colors instead of hardcoding values & why are you using **!important** at multiple places

**Comment by sanketr43** [comment]
okay. will add the missing variable classes for the colors. The !important is used because those are specific overriding utility classes. like margin padding etc. that's why it is a top priority class if applied.

**Comment by sanket4120** [comment]
Ok cant this be solved by placing this file after all other files or by creating separate file for margin, padding & then placing that files after all files

**Review by sanket4120 — APPROVED** [review]
Rest looks good

**Pull request merged**
